icons: &icons Iosevka Nerd Font Mono:pixelsize=48

bar:
  height: 64
  location: bottom
  background: 222222ff
  foreground: dfdfdfff
  font: Iosevka Nerd Font:size=24
  spacing: 8
  margin: 16

  left:
    - clock:
        date-format: "%a %d/%m"
        time-format: "%H:%M"
        content:
          - string: {text: "{date} {time}", deco: { stack: [underline: { size: 2, color: 0a6cf5ff }] }}
    - script:
        path: /home/mettz/.cargo/bin/yambar-hyprland-wses
        anchors:
          ws_focused: &ws_focused fba922ff
          ws_active: &ws_active ffaa00ff
          ws_empty: &ws_empty 555555ff
          ws_other: &ws_other bbbbbbff
          ws_1: &ws_1 "I"
          ws_2: &ws_2 "II"
          ws_3: &ws_3 "III"
          ws_4: &ws_4 "IV"
          ws_5: &ws_5 "V"
          ws_6: &ws_6 "VI"
          ws_7: &ws_7 "VII"
          ws_8: &ws_8 "VIII"
          ws_9: &ws_9 "IX"
        content:
          list:
            spacing: 6
            items:
              - map:
                  default:
                    string: { text: *ws_1, foreground: *ws_other }
                  conditions:
                    workspace_count < 2:
                      empty: {}
                    workspace_1_focused:
                      string: { text: *ws_1, foreground: *ws_focused }
                    workspace_1_active:
                      string: { text: *ws_1, foreground: *ws_active }
                    workspace_1_windows == 0:
                      string: { text: *ws_1, foreground: *ws_empty }
              - map:
                  default:
                    string: { text: *ws_2, foreground: *ws_other }
                  conditions:
                    workspace_count < 3:
                      empty: {}
                    workspace_2_focused:
                      string: { text: *ws_2, foreground: *ws_focused }
                    workspace_2_active:
                      string: { text: *ws_2, foreground: *ws_active }
                    workspace_2_windows == 0:
                      string: { text: *ws_2, foreground: *ws_empty }
              - map:
                  default:
                    string: { text: *ws_3, foreground: *ws_other }
                  conditions:
                    workspace_count < 4:
                      empty: {}
                    workspace_3_focused:
                      string: { text: *ws_3, foreground: *ws_focused }
                    workspace_3_active:
                      string: { text: *ws_3, foreground: *ws_active }
                    workspace_3_windows == 0:
                      string: { text: *ws_3, foreground: *ws_empty }
              - map:
                  default:
                    string: { text: *ws_4, foreground: *ws_other }
                  conditions:
                    workspace_count < 5:
                      empty: {}
                    workspace_4_focused:
                      string: { text: *ws_4, foreground: *ws_focused }
                    workspace_4_active:
                      string: { text: *ws_4, foreground: *ws_active }
                    workspace_4_windows == 0:
                      string: { text: *ws_4, foreground: *ws_empty }
              - map:
                  default:
                    string: { text: *ws_5, foreground: *ws_other }
                  conditions:
                    workspace_count < 6:
                      empty: {}
                    workspace_5_focused:
                      string: { text: *ws_5, foreground: *ws_focused }
                    workspace_5_active:
                      string: { text: *ws_5, foreground: *ws_active }
                    workspace_5_windows == 0:
                      string: { text: *ws_5, foreground: *ws_empty }
              - map:
                  default:
                    string: { text: *ws_6, foreground: *ws_other }
                  conditions:
                    workspace_count < 7:
                      empty: {}
                    workspace_6_focused:
                      string: { text: *ws_6, foreground: *ws_focused }
                    workspace_6_active:
                      string: { text: *ws_6, foreground: *ws_active }
                    workspace_6_windows == 0:
                      string: { text: *ws_6, foreground: *ws_empty }
              - map:
                  default:
                    string: { text: *ws_7, foreground: *ws_other }
                  conditions:
                    workspace_count < 8:
                      empty: {}
                    workspace_7_focused:
                      string: { text: *ws_7, foreground: *ws_focused }
                    workspace_7_active:
                      string: { text: *ws_7, foreground: *ws_active }
                    workspace_7_windows == 0:
                      string: { text: *ws_7, foreground: *ws_empty }
              - map:
                  default:
                    string: { text: *ws_8, foreground: *ws_other }
                  conditions:
                    workspace_count < 9:
                      empty: {}
                    workspace_8_focused:
                      string: { text: *ws_8, foreground: *ws_focused }
                    workspace_8_active:
                      string: { text: *ws_8, foreground: *ws_active }
                    workspace_8_windows == 0:
                      string: { text: *ws_8, foreground: *ws_empty }
              - map:
                  default:
                    string: { text: *ws_9, foreground: *ws_other }
                  conditions:
                    workspace_count < 10:
                      empty: {}
                    workspace_9_focused:
                      string: { text: *ws_9, foreground: *ws_focused }
                    workspace_9_active:
                      string: { text: *ws_9, foreground: *ws_active }
                    workspace_9_windows == 0:
                      string: { text: *ws_9, foreground: *ws_empty }
    - foreign-toplevel:
       content:
         map:
           conditions:
             ~activated: {empty: {}}
             activated:
               - string: {text: "{app-id}: "}
               - string: {text: "{title}", max: 40}

  right:
    - network:
        name: wlan0
        poll-interval: 5000
        content:
          map:
            default: {string: {text: "<>", foreground: ffffff66}}
            conditions:
              state == down: {string: {text: "", foreground: ff0000ff}}
              state == up:
                list:
                  deco: { stack: [underline: { size: 2, color: 749bf0ff }] }
                  right-spacing: 10
                  items:
                    - map:
                        conditions:
                          signal >= -50:
                            list:
                              left-spacing: 10
                              items:
                                - string: {text: "󰤨", foreground: 749bf0ff, font: *icons}
                          signal >= -60:
                            list:
                              left-spacing: 10
                              items:
                                - string: {text: "󰤥", foreground: 749bf0ff, font: *icons}
                          signal >= -70:
                            list:
                              left-spacing: 10
                              items:
                                - string: {text: "󰤢", foreground: 749bf0ff, font: *icons}
                          signal >= -80:
                            list:
                              left-spacing: 10
                              items:
                                - string: {text: "󰤟", foreground: 749bf0ff, font: *icons}
                          signal >= -90:
                            list:
                              left-spacing: 10
                              items:
                                - string: {text: "󰤯", foreground: 749bf0ff, font: *icons}
                    - string: {text: "{ssid}"}
    - battery:
        name: BAT1
        poll-interval: 30000
        anchors:
          discharging: &discharging
            list:
              right-spacing: 10
              items:
                - ramp:
                    tag: capacity
                    items:
                      - string: {text: , foreground: 6c9956ff, font: *icons}
                      - string: {text: , foreground: 6c9956ff, font: *icons}
                      - string: {text: , foreground: 6c9956ff, font: *icons}
                      - string: {text: , foreground: 6c9956ff, font: *icons}
                      - string: {text: , foreground: 6c9956ff, font: *icons}
                      - string: {text: , foreground: 6c9956ff, font: *icons}
                      - string: {text: , foreground: 6c9956ff, font: *icons}
                      - string: {text: , foreground: 6c9956ff, font: *icons}
                      - string: {text: , foreground: 6c9956ff, font: *icons}
                      - string: {text: , foreground: 6c9956ff, font: *icons}
                - map:
                    default:
                      list:
                        right-spacing: 0
                        items:
                          - string: {text: "00", foreground: 3d3d3dff}
                          - string: {text: "{capacity}%"}
                    conditions:
                      capacity == 100:
                        - string: {text: "{capacity}%"}
                      capacity >= 10:
                        list:
                          right-spacing: 0
                          items:
                            - string: {text: "0", foreground: 3d3d3dff}
                            - string: {text: "{capacity}%"}
        content:
          map:
            deco: { stack: [underline: { size: 2, color: 6c9956ff }] }
            conditions:
              state == unknown:
                <<: *discharging
              state == discharging:
                <<: *discharging
              state == charging:
                - string: {text: , foreground: 6c9956ff, font: *icons}
                - string: {text: " {capacity}%"}
              state == full:
                - string: {text: , font: *icons}
                - string: {text: " {capacity}% full"}
              state == "not charging":
                <<: *discharging
    - backlight:
       name: intel_backlight
       content: 
        list:
          right-spacing: 10
          deco: { stack: [underline: { size: 2, color: e3e66cff }] } 
          items:
            - string: {text: , foreground: e3e66cff, font: Iosevka Nerd Font Mono:pixelsize=32 }
            - map:
                default:
                  list:
                    right-spacing: 0
                    items:
                      - string: {text: "00", foreground: 333333ff}
                      - string: {text: "{percent}%"}
                conditions:
                  percent == 100:
                    - string: {text: "{percent}%"}
                  percent >= 10:
                    list:
                      right-spacing: 0
                      items:
                        - string: {text: "0", foreground: 333333ff}
                        - string: {text: "{percent}%"}
    - pipewire:
       content:
         map:
           conditions:
             type == "sink":
               map:
                 deco: { stack: [underline: { size: 2, color: 9f78e1ff }] } 
                 conditions:
                   muted: 
                     list:
                       right-spacing: 10
                       items:
                         - string: {text: "󰝟", foreground: 9778e1ff, font: *icons}
                         - string: {text: "Mute"}
                   ~muted: 
                     list:
                       right-spacing: 10 
                       items:
                         - ramp:
                             tag: linear_volume
                             items:
                               - string: {text: , foreground: 9f78e1ff, font: *icons}
                               - string: {text: , foreground: 9f78e1ff, font: *icons}
                               - string: {text: , foreground: 9f78e1ff, font: *icons}
                         - map:
                             default:
                               list:
                                 right-spacing: 0
                                 items:
                                   - string: {text: "00", foreground: 3d3d3dff}
                                   - string: {text: "{linear_volume}%"}
                             conditions:
                               linear_volume == 100:
                                 - string: {text: "{linear_volume}%"}
                               linear_volume >= 10:
                                 list:
                                   right-spacing: 0
                                   items:
                                     - string: {text: "0", foreground: 3d3d3dff}
                                     - string: {text: "{linear_volume}%"}

    - mem:
       poll-interval: 2000
       content:
         list:
           deco: { stack: [underline: { size: 2, color: e69353ff }] }
           right-spacing: 10
           items:
             - string: {text: "", foreground: e69353ff, font: Iosevka Nerd Font Mono:pixelsize=36} 
             - map:
                 default:
                   list:
                     right-spacing: 0
                     items:
                       - string: {text: "00", foreground: 3d3d3dff}
                       - string: {text: "{percent_used}%"}
                 conditions:
                   percent_used == 100:
                     - string: {text: "{percent_used}%"}
                   percent_used >= 10:
                     list:
                       right-spacing: 0
                       items:
                         - string: {text: "0", foreground: 3d3d3dff}
                         - string: {text: "{percent_used}%"}

    - cpu:
       poll-interval: 2000
       content:
         map:
           deco: { stack: [underline: { size: 2, color: f90000ff }] }
           conditions:
             id < 0:
               list:
                 right-spacing: 10
                 items:
                   - string: {text: "", foreground: f90000ff, font: *icons} 
                   - map:
                       default:
                         list:
                           right-spacing: 0
                           items:
                             - string: {text: "00", foreground: 3d3d3dff}
                             - string: {text: "{cpu}%"}
                       conditions:
                         cpu == 100:
                           - string: {text: "{cpu}%"}
                         cpu >= 10:
                           list:
                             right-spacing: 0
                             items:
                               - string: {text: "0", foreground: 3d3d3dff}
                               - string: {text: "{cpu}%"}
