[alacritty.files]
alacritty = "~/.config/alacritty"

[dunst.files]
dunst = "~/.config/dunst"

[fish.files]
fish = "~/.config/fish"

[git.files]
git = "~/.config/git"

[hypr.files]
hypr = "~/.config/hypr"

[waybar.files]
waybar = "~/.config/waybar"

[wlogout.files]
wlogout = "~/.config/wlogout"

[wofi.files]
wofi = "~/.config/wofi"

[yambar.files]
yambar = "~/.config/yambar"

[zathura.files]
zathura = "~/.config/zathura"

[tiling]
depends = ["dunst", "hypr", "waybar", "wlogout", "wofi"]

[shell]
depends = ["alacritty", "fish", "git"]

[apps]
depends = ["zathura"]
