[alacritty.files]
alacritty = "~/.config/alacritty"

[dunst.files]
dunst = "~/.config/dunst"

[eww.files]
eww = "~/.config/eww"
"eww/eww.yuck" = { target = "~/.config/eww/eww.yuck", type = "symbolic" }

[fish.files]
fish = "~/.config/fish"

[keyd.files]
keyd = { target = "/etc/keyd", type = "symbolic", owner = "root" }

[git.files]
git = "~/.config/git"

[hypr.files]
hypr = "~/.config/hypr"

[waybar.files]
waybar = "~/.config/waybar"

[wlogout.files]
wlogout = "~/.config/wlogout"

[wofi.files]
wofi = "~/.config/wofi"

[yambar.files]
yambar = "~/.config/yambar"

[zathura.files]
zathura = "~/.config/zathura"

[system]
depends = ["keyd"]

[tiling]
depends = ["dunst", "eww", "hypr", "system", "waybar", "wlogout", "wofi"]

[shell]
depends = ["alacritty", "fish", "git"]

[apps]
depends = ["zathura"]
